#ifndef GUARD_CC_VERSION
#define GUARD_CC_VERSION

enum GameVersions
{
    CC_GAME_VERSION_1 = 1,
};

#define CC_GAME_VERSION CC_GAME_VERSION_1

#define CC_VERSION_1_BANNER_COUNT 3

enum Banner
{
    BANNER_INDOMITABILITY_OF_THE_UNBREAKABLE_SPIRIT,
    BANNER_FURY_OF_THE_EARTHERN_CORE,
    BANNER_MEMORIES_OF_MONTHS_PAST,
    BANNER_COUNT,
};


#endif
