#ifndef GUARD_CC_VERSION
#define GUARD_CC_VERSION

enum GameVersions
{
    CC_GAME_VERSION_1 = 1,
};

#define CC_GAME_VERSION CC_GAME_VERSION_1

#define CC_VERSION_1_BANNER_COUNT 4

enum Banner
{
    BANNER_ITEMS,
    BANNER_INDOMITABILITY_OF_THE_UNBREAKABLE_SPIRIT,
    BANNER_FURY_OF_THE_EARTHEN_CORE,
    BANNER_MEMORIES_OF_MONTHS_PAST,
    BANNER_COUNT,
};

#define PULL_1_COST     50
#define PULL_10_COST    PULL_1_COST * 10

#define ODDS_6_STAR 100
#define ODDS_5_STAR 4
#define PITY_6_STAR 10
#define PITY_5_STAR 3

#define BALL_4_STAR BALL_POKE
#define BALL_5_STAR BALL_PREMIER
#define BALL_6_STAR BALL_CHERISH

#endif
