#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_SATSUKI,
    SP_NAME_CHISA,
    SP_NAME_ARDELIA,
    SP_NAME_ARCANE,
    SP_NAME_CARNELIAN,
    SP_NAME_CHEN,
    SP_NAME_ELYSIUM,
    SP_NAME_ENDMIN,
    SP_NAME_FIAMETTA,
    SP_NAME_GILBERTA,
    SP_NAME_GLADIIA,
    SP_NAME_IRENE,
    SP_NAME_LAEVATAIN,
    SP_NAME_MIFU,
    SP_NAME_NIAN,
    SP_NAME_PENANCE,
    SP_NAME_PERLICA,
    SP_NAME_POG,
    SP_NAME_PRAMANIX,
    SP_NAME_SHU,
    SP_NAME_SKADI,
    SP_NAME_SPECTER,
    SP_NAME_TANGTANG,
    SP_NAME_ULPIANUS,
    SP_NAME_XAIHI,
    SP_NAME_ZHUANG,
    SP_NAME_TIANA,
    SP_NAME_GUARD,
    SP_NAME_COUNT,
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
